### ISSUE TITLE
less-than dataizes twice

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-hamcrest#128]
@Graur please take a look at this case
```
[] > less-than
  assert-that > @
    seq
      QQ.io.stdout "SEQ STARTING\n"
      100
    $.less-than 300
```
This code works this way
```
[INFO] Running EOorg.EOeolang.EOthreads.EOless_thanTest
SEQ STARTING
SEQ STARTING
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in EOorg.EOeolang.EOthreads.EOless_thanTest
```
I don't guess it must work this way.

**Comment by Graur** [comment]
@levBagryansky Indeed, this is a bug

**Comment by Graur** [comment]
@includealex take care of this, please

**Comment by includealex** [comment]
@Graur sure.

**Comment by includealex** [comment]
@Graur @levBagryansky  I think that problem is not in `less_than` but in `lt` or `seq`. This program
```eo
+alias org.eolang.io.stdout
+package sandbox

[x] > foo
  lt. > @
    x
    4

[] > app
  seq > @
    seq > x
      stdout "SEQ STARTING\n"
      1000
    foo x

```
gives such an output:
```
SEQ STARTING
SEQ STARTING
SEQ STARTING
Exception in thread "main" java.lang.IllegalStateException: Runtime dataization failure
        at org.eolang.Main.run(Main.java:191)
        at org.eolang.Main.main(Main.java:98)
```
If we make a simple modification of this program (just change lt. with gt.), program will look like:
```eo
+alias org.eolang.io.stdout
+package sandbox

[x] > foo
  gt. > @
    x
    4

[] > app
  seq > @
    seq > x
      stdout "SEQ STARTING\n"
      1000
    foo x

```
In this case an output will be:
```
SEQ STARTING
SEQ STARTING
```

**Comment by Graur** [comment]
@includealex @levBagryansky  Thanks! 
So, who can create a new issue in EO repository?

**Comment by levBagryansky** [comment]
@yegor256 can you transfer the issue  to eo?
