### ISSUE TITLE
contains-string fails in eo repo

### ISSUE THREAD

**Issue by levBagryansky** [objectionary/eo-hamcrest#212]
The test below is fails in eo repository. 
```
[] > catch-contains-string
  assert-that > @
    "abpba"
    $.contains-string
      "aboba"
```
with error 
```
org.eolang.ExUnset: Error at "memory.enclosure" attribute
        at org.eolang.AtNamed.get(AtNamed.java:99)
        at org.eolang.PhDefault.attr(PhDefault.java:263)
        at org.eolang.PhLocated.attr(PhLocated.java:117)
        at org.eolang.PhOnce.attr(PhOnce.java:91)
```
@Graur please take a look

**Comment by Graur** [comment]
@levBagryansky Indeed, it's a bug. Thanks!

**Comment by 0pdd** [comment]
@levBagryansky the puzzle [#215](https://github.com/objectionary/eo-hamcrest/issues/215) is still not solved.
