### ISSUE TITLE
assert-that.eo:256-258: Here we got an object printed...

### ISSUE THREAD

**Issue by 0pdd** [objectionary/eo-hamcrest#78]
The puzzle `3-30c88f18` from #3 has to be resolved: 

https://github.com/objectionary/eo-hamcrest/blob/f4ffbf4c557f941202434277537564b637a0da4d/src/main/eo/org/eolang/hamcrest/assert-that.eo#L256-L258

The puzzle was created by @Graur on 18-Jul-22. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
I can't create GITHUB labels ``. Most likely I don't have necessary permissions to `objectionary/eo-hamcrest` repository. Please, make sure @0pdd user is in the [list of collaborators](https://github.com/objectionary/eo-hamcrest/settings/collaboration):

```Octokit::Forbidden
POST https://api.github.com/repos/objectionary/eo-hamcrest/issues/78/labels: 403 - Must have admin rights to Repository. // See: https://docs.github.com/rest/reference/issues#add-labels-to-an-issue
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/response/raise_error.rb:14:in `on_complete'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/middleware.rb:18:in `block in call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/response.rb:42:in `on_complete'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-2.3.0/lib/faraday/connection.rb:281:in `post'
/app/vendor/bundle/ruby/2.7.0/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/connection.rb:156:in `request'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/connection.rb:28:in `post'
/app/vendor/bundle/ruby/2.7.0/gems/octokit-4.25.1/lib/octokit/client/labels.rb:127:in `add_labels_to_an_issue'
/app/objects/vcs/github.rb:82:in `add_labels_to_an_issue'
/app/objects/tickets/tagged_tickets.rb:46:in `submit'
/app/objects/tickets/commit_tickets.rb:36:in `submit'
/app/objects/tickets/emailed_tickets.rb:35:in `submit'
/app/objects/tickets/sentry_tickets.rb:45:in `submit'
/app/objects/puzzles.rb:136:in `block in expose'
/app/objects/puzzles.rb:126:in `loop'
/app/objects/puzzles.rb:126:in `expose'
/app/objects/puzzles.rb:38:in `deploy'
/app/objects/jobs/job.rb:38:in `proceed'
/app/objects/jobs/job_starred.rb:32:in `proceed'
/app/objects/jobs/job_recorded.rb:31:in `proceed'
/app/objects/jobs/job_emailed.rb:33:in `proceed'
/app/objects/jobs/job_commiterrors.rb:33:in `proceed'
/app/objects/jobs/job_detached.rb:48:in `exclusive'
/app/objects/jobs/job_detached.rb:36:in `block in proceed'
/app/objects/jobs/job_detached.rb:36:in `fork'
/app/objects/jobs/job_detached.rb:36:in `proceed'
/app/0pdd.rb:517:in `process_request'
/app/0pdd.rb:355:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-protection-2.2.0/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/logger.rb:17:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/common_logger.rb:38:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:255:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:248:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `block in call'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1768:in `synchronize'
/app/vendor/bundle/ruby/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.4/lib/rack/handler/webrick.rb:95:in `service'
/app/vendor/ruby-2.7.6/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.7.6/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.7.6/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'
```
